services:
  mongodb:
    image: mongo
    container_name: dd_mongodb
    environment:
      MONGO_INITDB_DATABASE: dd_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mean_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    image: manikprakash/backend:latest   
    container_name: dd_backend
    environment:
      PORT: 8080
      MONGO_URL: mongodb://mongodb:27017/dd_db      
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mean_network

  frontend:
    image: manikprakash/frontend:latest 
    container_name: dd_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mean_network

volumes:
  mongo_data:

networks:
  mean_network:
    driver: bridge
